import Vue from 'vue'
import Vuex from 'vuex'
Vue.use(Vuex)

const actions = {}
const mutations = {
    ADD_PERSON(state, value) {
        console.log('mutations中的ADD_PERSON被调用了')
        state.wholeData.unshift(value)
        console.log(value);
    },
    Change_PERSON(state, value) {
        console.log('mutations中的Change_PERSON被调用了')
        for (let i = 0; i < state.wholeData.length; i++) {
            if (state.wholeData[i].num == value.num) {
                state.wholeData[i] = value
                break;
            }
        }
    },
}
const state = {
    tableData: [{
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院1",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院2",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院3",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },
        {
            num: "",
            name: "王小明",
            term: "2021秋",
            course: "java",
            college: ["计算机学院1"],
            school: "长江大学工程技术学院",
            major: ["软件工程"],
            class: ["21级计算机科学与技术2班"],
            teacher: ["张老师"],
            homeWorks: ["离散数学"],
            updataPerson: "李老师",
            term1: "2021",
            term2: "秋季",
            time: "2021-09-26 23:01:56",
        },

    ],
}
const getters = {}

//创建并暴露store
export default new Vuex.Store({
    actions,
    mutations,
    state,
    getters
})